import test from 'node:test';import assert from 'node:assert/strict';import PizZip from 'pizzip';import {PDFDocument,StandardFonts} from 'pdf-lib';
import {manifestFingerprint,validatePublicInsight,mergePublicChunks,hash,artifactIsApproved,publicFileUrl,zipName,splitPublicText,knowledgeFailureState} from '../src/services/process-knowledge-rules.js';
import {inspectTemplate,renderTemplate} from '../src/services/template-renderer.js';
import {officeToPdf,previewPage} from '../src/services/document-preview.js';
import {inspectDocxBlanks,fillDocxBlanks} from '../src/services/annex-fields.js';
const url='https://community.secop.gov.co/Public/Archive/RetrieveFile/Index?DocumentId=123';
test('public cache ignores synchronization timestamps and order; invalidates changed source metadata',()=>{const a={id:'a',file_name:'pliego.pdf',download_url_text:url},b={...a,id:'b'};assert.equal(manifestFingerprint([a,b]),manifestFingerprint([{...b,updated_at:'tomorrow'},a]));assert.notEqual(manifestFingerprint([a]),manifestFingerprint([{...a,sha256:'new'}]));assert.notEqual(manifestFingerprint([a]),manifestFingerprint([a,b]));});
test('public source accepts only official file downloads',()=>{assert.equal(publicFileUrl({download_url:{url}}),url);for(const v of ['http://community.secop.gov.co/Public/Archive/RetrieveFile/Index?DocumentId=123',url.replace('community.secop.gov.co','community.secop.gov.co.evil.test'),url.replace('Public/Archive/RetrieveFile/Index','STS/Users/Login/Index')])assert.equal(publicFileUrl({download_url_text:v}),null);});
test('facts require literal source quotes; roles include mixed documents and chunk deduplication',()=>{const source='El plazo de presentación es el 20 de septiembre de 2026.';const value={document_role:'informative',summary:'Plazo',facts:[{category:'schedule',label:'Plazo',value:'20 de septiembre de 2026',quote:source}]};const result=validatePublicInsight(value,source);assert.throws(()=>validatePublicInsight({...value,facts:[{...value.facts[0],value:'2030'}]},source));assert.throws(()=>validatePublicInsight(value,'Otro documento sin esa evidencia.'));const m=mergePublicChunks({a:result,b:result},[{name:'campo'}]);assert.equal(m.document_role,'mixed');assert.equal(m.facts.length,1);const chunks=splitPublicText('a'.repeat(45000));assert.equal(chunks.length,3);assert.equal(chunks.at(-1).length,9800);});
test('approval binds both original and rendered preview and rejects missing values',()=>{const g={file_hash_sha256:'a',validation_issues:[{code:'review_overlay_position'}]},r={source_hash:'a',preview_hash:'p'},p={source_hash:'a',pdf_hash:'p'};assert.ok(artifactIsApproved(g,r,p));assert.ok(!artifactIsApproved({...g,file_hash_sha256:'b'},r,p));assert.ok(!artifactIsApproved(g,r,{...p,pdf_hash:'new'}));assert.ok(!artifactIsApproved({...g,validation_issues:[{code:'required_value_missing'}]},r,p));assert.ok(!zipName('../../bad/file.pdf').includes('/'));});
test('DOCX fills each distinct blank in one run and protects XML',()=>{const xml='<w:p><w:r><w:t>Razón social: ______ NIT: ______</w:t></w:r></w:p>';const f=inspectDocxBlanks(xml);assert.equal(f.length,2);const issues=[];const out=fillDocxBlanks(xml,f,{[f[0].name]:'A & B',[f[1].name]:'123'},{},issues);assert.ok(out.includes('A &amp; B NIT: 123'));assert.equal(issues.length,0);});
function office(type){const z=new PizZip();z.file('[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${type==='docx'?'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>':'<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'}</Types>`);z.file('_rels/.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="${type==='docx'?'word/document.xml':'xl/workbook.xml'}"/></Relationships>`);if(type==='docx'){z.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Razón social: {legal_name}</w:t></w:r></w:p><w:sectPr/></w:body></w:document>');}else{z.file('xl/workbook.xml','<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Oferta" sheetId="1" r:id="rId1"/></sheets></workbook>');z.file('xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');z.file('xl/worksheets/sheet1.xml','<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>{legal_name}</t></is></c><c r="B1"><f>1+1</f><v>2</v></c></row></sheetData></worksheet>');}return z.generate({type:'nodebuffer'});}
for(const type of ['docx','xlsx'])test(`${type.toUpperCase()} autofill renders an actual PDF and visible page`,{timeout:65000},async()=>{const buffer=office(type),fields=await inspectTemplate(buffer,type);assert.equal(fields.length,1);const mapping=Object.fromEntries(fields.map(f=>[f.name,'legal_name']));const result=await renderTemplate({buffer,templateType:type,values:{legal_name:'Empresa de prueba'},mapping,fieldSchema:fields});assert.equal(result.issues.length,0);const pdf=await officeToPdf(result.buffer,'.'+type);assert.equal((await PDFDocument.load(pdf)).getPageCount(),1);const png=await previewPage(pdf,1);assert.equal(png.subarray(1,4).toString(),'PNG');});
test('XLSX cannot overwrite a formula or turn an input into a formula',async()=>{const buffer=office('xlsx');const fields=await inspectTemplate(buffer,'xlsx');const result=await renderTemplate({buffer,templateType:'xlsx',fieldSchema:[...fields,{name:'bad',sheet:'xl/worksheets/sheet1.xml',cell:'B1',type:'xlsx_cell'}],values:{[fields[0].name]:'=HYPERLINK("evil")',bad:'overwrite'}});const xml=new PizZip(result.buffer).file('xl/worksheets/sheet1.xml').asText();assert.ok(xml.includes('<f>1+1</f>'));assert.ok(xml.includes('=HYPERLINK(&quot;evil&quot;)'));assert.ok(result.issues.some(i=>i.code==='formula_cell_protected'));});
test('PDF underscore fields are located and oversized values remain blocked',async()=>{const pdf=await PDFDocument.create(),p=pdf.addPage([595,842]),font=await pdf.embedFont(StandardFonts.Helvetica);p.drawText('NIT: ____________________',{x:40,y:770,font,size:12});const buffer=Buffer.from(await pdf.save()),fields=await inspectTemplate(buffer,'pdf_form');assert.equal(fields.length,1);const ok=await renderTemplate({buffer,templateType:'pdf_form',fieldSchema:fields,values:{[fields[0].name]:'123456789'}});assert.ok(!ok.issues.some(i=>i.code==='value_overflows_field'));const overflow=await renderTemplate({buffer,templateType:'pdf_form',fieldSchema:fields,values:{[fields[0].name]:'A'.repeat(200)}});assert.ok(overflow.issues.some(i=>i.code==='value_overflows_field'));});
test('Office preview refuses linked external content',async()=>{const z=new PizZip(office('docx'));z.file('word/_rels/document.xml.rels','<Relationships><Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" TargetMode="External" Target="https://example.test/private"/></Relationships>');await assert.rejects(officeToPdf(z.generate({type:'nodebuffer'}),'.docx'),/externamente/);});

test('provider outage preserves queued work and completed chunks without exhausting document retries',()=>{let attempts=0;for(let n=0;n<8;n++){const state=knowledgeFailureState({code:'AI_PROVIDER_WAIT',retryAfter:300},attempts);assert.equal(state.status,'queued');assert.equal(state.retryAfter,300);attempts=state.attempts;}assert.equal(attempts,0);assert.equal(knowledgeFailureState(new Error('Invalid citation'),2).status,'error');assert.equal(knowledgeFailureState({permanent:true},0).status,'error');});

test('XLSX preview freezes external formula values only in its disposable copy and keeps internal formulas',async()=>{
 const {officePreviewSource}=await import('../src/services/office-preview-source.js');
 const z=new PizZip(office('xlsx'));
 z.file('xl/externalLinks/externalLink1.xml','<externalLink/>');
 z.file('xl/externalLinks/_rels/externalLink1.xml.rels','<Relationships><Relationship Type="externalLinkPath" TargetMode="External" Target="file:///private.xlsx"/></Relationships>');
 z.file('xl/worksheets/sheet1.xml',z.file('xl/worksheets/sheet1.xml').asText().replace('<f>1+1</f>','<f>[1]Other!A1</f>').replace('</row>','<c r="C1"><f>2+2</f><v>4</v></c></row>'));
 const source=z.generate({type:'nodebuffer'}),rendered=new PizZip(officePreviewSource(source,'.xlsx'));
 assert.ok(new PizZip(source).file('xl/externalLinks/externalLink1.xml'));assert.equal(rendered.file('xl/externalLinks/externalLink1.xml'),null);
 const xml=rendered.file('xl/worksheets/sheet1.xml').asText();assert.ok(!xml.includes('[1]'));assert.ok(xml.includes('<v>2</v>'));assert.ok(xml.includes('<f>2+2</f>'));
 z.file('xl/worksheets/sheet1.xml',z.file('xl/worksheets/sheet1.xml').asText().replace('<v>2</v>',''));
 assert.throws(()=>officePreviewSource(z.generate({type:'nodebuffer'}),'.xlsx'),/valor guardado/);
});

test('official bracket placeholders split across Word runs are filled without rewriting surrounding clauses',()=>{
 const xml='<w:p><w:r><w:t>Yo, [Nombre del repre</w:t></w:r><w:r><w:t>sentante legal] de [nombre del Proponente], acepto [1].</w:t></w:r></w:p>';
 const fields=inspectDocxBlanks(xml);assert.equal(fields.length,2);assert.equal(fields[0].suggested_source,'representative_name');assert.equal(fields[1].suggested_source,'legal_name');
 const issues=[],out=fillDocxBlanks(xml,fields,{[fields[0].name]:'Ana & Co',[fields[1].name]:'Empresa de prueba'},{},issues);
 assert.ok(out.includes('Yo, Ana &amp; Co'));assert.ok(out.includes(' de Empresa de prueba, acepto [1].'));assert.ok(!out.includes('sentante legal'));assert.equal(issues.length,0);
});

test('signature label below a blank is an image field; its saved image renders inside DOCX only when supplied',async()=>{
 const z=new PizZip(office('docx'));z.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>________________</w:t></w:r></w:p><w:p><w:r><w:t>Firma del representante legal</w:t></w:r></w:p></w:body></w:document>');
 const buffer=z.generate({type:'nodebuffer'}),fields=await inspectTemplate(buffer,'docx');assert.equal(fields.length,1);assert.equal(fields[0].suggested_source,'signature_image');
 const unsigned=await renderTemplate({buffer,templateType:'docx',values:{},fieldSchema:fields});assert.ok(unsigned.issues.some(i=>i.code==='signature_missing'));
 const signature={buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64'),mime:'image/png',hash:'test'};
 const signed=await renderTemplate({buffer,templateType:'docx',values:{},fieldSchema:fields,signature});const zip=new PizZip(signed.buffer);assert.ok(zip.file('word/media/cernoia-signature-test.png'));assert.ok(zip.file('word/document.xml').asText().includes('<w:drawing>'));assert.ok(!signed.issues.some(i=>i.code==='signature_missing'||i.code==='required_value_missing'));
 assert.ok((await PDFDocument.load(await officeToPdf(signed.buffer,'.docx'))).getPageCount()>0);
});

test('annex catalog separates public supporting documents and matches requested templates generically',async()=>{
 const {annexRole,matchingAnnexes}=await import('../src/services/annex-catalog.js');
 for(const name of ['CDP 82362.pdf','ESTUDIOS PREVIOS.pdf','ANEXO TÉCNICO.pdf'])assert.equal(annexRole(name),'informative');
 const entries=['ANEXO 9 MULTAS Y SANCIONES.docx','ANEXO AUTORIZACION TRATAMIENTO DE DATOS PERSONALES.docx'].map((filename,id)=>({id,filename,role:annexRole(filename)}));
 assert.deepEqual(matchingAnnexes({requirement_name:'El proponente deberá diligenciar Anexo Multas y sanciones firmado por el representante legal'},entries),[0]);
 assert.deepEqual(matchingAnnexes({requirement_name:'Autorización de tratamiento de datos personales'},entries),[1]);
 assert.deepEqual(matchingAnnexes({requirement_name:'Certificado de antecedentes del representante legal'},entries),[]);
});
