import test from 'node:test';import assert from 'node:assert/strict';
import {validateSemanticMetadata as validate,mergeSemanticMetadata as merge} from '../src/services/document-metadata-validation.js';
const raw={document_type:'bank_certificate',document_type_label:'Certificado bancario',type_quote:'Certificado bancario',type_confidence:'high',issue_date:'2026-09-22',issue_quote:'Se expide en Bogotá el día 22 de septiembre del año 2026.',issue_confidence:'high',expiration_date:null,expiration_quote:'',expiration_confidence:'high',expiration_kind:'not_stated',validity_days:null,validity_quote:''};
const text='Certificado bancario. Se expide en Bogotá el día 22 de septiembre del año 2026.';
test('semantic classification accepts quoted type and individual long Spanish date',()=>{const a=validate(raw,text);assert.equal(a.document_type,'bank_certificate');assert.equal(a.issue_date,'2026-09-22');assert.deepEqual(a.issues,[]);assert.equal(a.expiration_date,null);});
test('unsupported dates and invented quotations cannot fill fields',()=>{assert.equal(validate({...raw,issue_date:'2026-09-23'},text).issue_date,null);assert.equal(validate({...raw,type_quote:'Documento de identidad'},text).document_type,null);assert.equal(validate({...raw,issue_confidence:'low'},text).issue_date,null);});
test('expiry is independent and never inferred from issue without explicit policy',()=>{const a=validate(raw,text);const d={document_type:'other_document',document_name:'scan',original_filename:'scan.pdf',review_status:'corrected'};assert.equal(merge(d,a).expiration_date,null);assert.equal(merge(d,a,{validity_days:30}).expiration_date,'2026-10-22');assert.equal(merge(d,a,{validity_days:30}).expiration_source,'policy');});
test('explicit expiration wins over policy and cannot precede issue',()=>{const r={...raw,expiration_kind:'explicit',expiration_date:'2026-12-22',expiration_quote:'Válido hasta el 22/12/2026'};const a=validate(r,text+' Válido hasta el 22/12/2026');assert.equal(merge({document_type:'auto_detect'},a,{validity_days:30}).expiration_date,'2026-12-22');assert.equal(validate({...r,expiration_date:'2025-12-22',expiration_quote:'Válido hasta el 22/12/2025'},text+' Válido hasta el 22/12/2025').expiration_date,null);});
test('manual meaningful corrections survive; other/empty confirmations are filled',()=>{const a=validate(raw,text);assert.equal(merge({document_type:'other_document',review_status:'corrected'},a).document_type,'bank_certificate');const m=merge({document_type:'rut',review_status:'corrected',issue_date:'2026-08-01',expiration_date:'2026-08-31'},a);assert.equal(m.document_type,'rut');assert.equal(m.issue_date,'2026-08-01');assert.equal(m.expiration_date,'2026-08-31');});
test('intentional clearing of a manually edited date stays empty',()=>{const a=validate(raw,text);assert.equal(merge({document_type:'bank_certificate',review_status:'corrected',metadata:{manual_metadata_fields:['issue_date','expiration_date']}},a,{validity_days:30}).issue_date,null);});
test('explicit duration uses each document issue date',()=>{const a=validate({...raw,expiration_kind:'duration',validity_days:90,validity_quote:'Válido por 90 días a partir de su expedición'},text+' Válido por 90 días a partir de su expedición');const result=merge({document_type:'other_document'},a);assert.equal(result.expiration_date,'2026-12-21');assert.equal(result.expiration_source,'document_duration');});

test('registration dates cannot stand in for document issue dates',()=>{const a=validate({...raw,issue_date:'2025-02-03',issue_quote:'Fecha de registro: 03 DE FEBRERO 2025'},text+' Fecha de registro: 03 DE FEBRERO 2025');assert.equal(a.issue_date,null);assert.ok(a.issues.length);});
