import test from 'node:test';
import assert from 'node:assert/strict';
import {sourceDate,processSchedule,officialProcessUrl,withProcessSchedule} from '../src/services/process-schedule.js';
const now=new Date('2026-09-15T18:00:00Z');
const dated={response_deadline:null,process_status:'Publicado',phase:'Presentación de oferta',raw_json:{fecha_de_recepcion_de:'2026-09-15T00:00:00.000'}};
test('recovers raw date without inventing hour or moving calendar day',()=>{const s=processSchedule(dated,now);assert.deepEqual(s.deadline,{value:'2026-09-15',precision:'date'});assert.equal(s.later_stage,false);assert.equal(s.code,'submission');});
test('prioritizes advanced official state over misleading offer phase',()=>{for(const [process_status,code] of [['Evaluación','evaluation'],['Seleccionado','selected'],['Adjudicado','awarded'],['Cancelado','cancelled']]) {const s=processSchedule({...dated,process_status},now);assert.equal(s.code,code);assert.equal(s.later_stage,true);}});
test('past calendar date is expired; exact hour expires within same day',()=>{assert.equal(processSchedule({...dated,raw_json:{fecha_de_recepcion_de:'2026-09-14T00:00:00.000'}},now).code,'expired');assert.equal(processSchedule({...dated,raw_json:{fecha_de_recepcion_de:'2026-09-15T12:00:00'}},now).code,'expired');});
test('missing deadline never becomes open from phase or aperture visibility',()=>{const s=processSchedule({phase:'Presentación de oferta',opening_status:'Abierto'},now);assert.equal(s.code,'unconfirmed');assert.equal(s.deadline,null);});
test('opening and award dates are milestones, never replacement offer deadlines',()=>{const s=processSchedule({raw_json:{fecha_de_apertura_de_respuesta:'2026-10-01T00:00:00.000',fecha_adjudicacion:'2026-10-02T00:00:00.000'}},now);assert.equal(s.deadline,null);assert.equal(s.milestones.length,2);});
test('interest phase does not fabricate registration deadline from generic responses',()=>{const s=processSchedule({...dated,phase:'Manifestación de interés (Menor Cuantía)'},now);assert.equal(s.code,'interest');assert.equal(s.interest_deadline,null);assert.equal(s.deadline_label,'Recepción de respuestas publicada');});
test('normalizes Colombia datetime and rejects invalid source dates',()=>{assert.deepEqual(sourceDate('2026-09-16T14:30:00.000'),{value:'2026-09-16T19:30:00.000Z',precision:'datetime'});assert.equal(sourceDate('2026-02-30T00:00:00.000'),null);assert.equal(sourceDate('No definido'),null);});
test('recovers official URL object and rejects unsafe links',()=>{const url='https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.1';assert.equal(officialProcessUrl('[object Object]',{url}),url);for(const url of ['javascript:alert(1)','https://evil.test/Public/','https://community.secop.gov.co.evil.test/Public/'])assert.equal(officialProcessUrl(url,null),null);});
test('does not expose raw source payload to frontend',()=>{const row=withProcessSchedule({...dated,schedule_source:dated.raw_json});assert.ok(!('schedule_source' in row));});

test('official login-only URLs fall back to public search, not a fictitious process link',()=>{const s=processSchedule({process_url:'[object Object]',raw_json:{urlproceso:{url:'https://community.secop.gov.co/STS/Users/Login/Index'}}},now);assert.equal(s.source_link_kind,'search');assert.ok(s.source_url.includes('ContractNoticeManagement'));});
