"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CheckCircle2, FileUp, Sparkles } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { DashboardSection } from "@/app/components/dashboard/shared";

type DemoAccess = { demo?: { demo_enabled?: boolean; membership_active?: boolean; demo_used?: boolean } };
type Props = { userId: string; navigate: (section: DashboardSection) => void };
const guideKey = (userId: string) => `cernoia:demo-guide-seen:${userId}`;
const starterDocuments = [["Cámara de Comercio", "Existencia y representación legal."], ["RUT", "Información tributaria actualizada."], ["Portafolio empresarial", "Servicios y líneas de negocio."], ["Experiencia", "Certificados, contratos o actas."], ["Estados financieros", "El período más reciente disponible."]];

export function DemoOnboardingGuide({ userId, navigate }: Props) {
  const [active, setActive] = useState(false); const [open, setOpen] = useState(false); const [step, setStep] = useState(0);
  useEffect(() => { let mounted = true; void apiFetch<DemoAccess>("/account/demo").then(({ demo }) => { if (!mounted) return; const isActive = Boolean(demo?.demo_enabled && !demo.membership_active && !demo.demo_used); setActive(isActive); if (isActive) { try { if (!window.localStorage.getItem(guideKey(userId))) setOpen(true); } catch { setOpen(true); } } }).catch(() => {}); return () => { mounted = false; }; }, [userId]);
  function closeGuide() { try { window.localStorage.setItem(guideKey(userId), "1"); } catch { /* storage disabled */ } setOpen(false); }
  function goTo(section: DashboardSection) { closeGuide(); navigate(section); }
  if (!active) return null;
  return <>
    <Card className="mb-6 overflow-hidden border-teal-200 bg-gradient-to-r from-[#0b5963] to-[#103f57] text-white shadow-sm"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-white/12 p-2.5"><BookOpen className="size-5 text-teal-100" /></div><div><div className="flex flex-wrap items-center gap-2"><Badge className="border-white/20 bg-white/12 text-white">Demo guiada</Badge><span className="text-sm text-teal-100">Tu cuenta está lista para comenzar</span></div><p className="mt-2 text-base font-semibold">Confirma los datos de tu empresa y prepara tus documentos.</p><p className="mt-1 max-w-2xl text-sm leading-5 text-slate-200">CernoIA no debe asumir el NIT ni el representante legal: primero verifica la identidad y luego carga la evidencia.</p></div></div><Button variant="secondary" className="shrink-0 bg-white text-[#0b5963] hover:bg-teal-50" onClick={() => { setStep(0); setOpen(true); }}><BookOpen /> Ver guía</Button></CardContent></Card>
    <Dialog open={open} onOpenChange={(nextOpen) => { if (!nextOpen) closeGuide(); else setOpen(true); }}><DialogContent className="max-h-[92svh] overflow-y-auto sm:max-w-2xl"><DialogHeader><div className="mb-1 flex items-center gap-2 text-sm font-medium text-teal-700"><span>Paso {step + 1} de 3</span><span className="h-1.5 flex-1 rounded-full bg-slate-100"><span className="block h-1.5 rounded-full bg-teal-600 transition-all" style={{ width: `${((step + 1) / 3) * 100}%` }} /></span></div><DialogTitle>{step === 0 ? "Antes de comenzar: confirma tu empresa" : step === 1 ? "Carga tus evidencias" : "Analiza una oportunidad"}</DialogTitle><DialogDescription>{step === 0 ? "CernoIA puede sugerir datos al leer documentos, pero no los confirma ni los cambia automáticamente. Verifica NIT, razón social y representante legal antes de continuar." : step === 1 ? "Desde Documentos puedes cargar archivos PDF, Word, Excel, imágenes y asignarles su tipo documental. La IA los leerá y actualizará tu matriz." : "Cuando la matriz tenga información, abre una oportunidad y selecciona Analizar oportunidad. El resultado depende de la evidencia disponible."}</DialogDescription></DialogHeader>
      {step === 0 && <div className="space-y-3 rounded-2xl border border-teal-100 bg-teal-50/60 p-4"><p className="text-sm font-semibold text-teal-950">Verifica estos datos y reúne este paquete inicial</p><div className="grid gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950"><p><strong>Identidad:</strong> NIT, razón social y nombre del representante legal.</p><p className="text-xs leading-5">Si alguno está vacío, ve a Configuración → Perfil IA → Identidad empresarial y complétalo. El NIT del documento debe coincidir con el que registres.</p></div><div className="grid gap-3 sm:grid-cols-2">{starterDocuments.map(([title, description]) => <div key={title} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-teal-700" /><div><p className="font-medium text-slate-900">{title}</p><p className="text-xs leading-5 text-slate-600">{description}</p></div></div>)}</div><p className="border-t border-teal-100 pt-3 text-xs leading-5 text-slate-600">Si aplica, agrega RUP, certificaciones, títulos profesionales, inventario de equipos y soportes de cobertura. No necesitas tenerlos todos para entrar, pero la evidencia será limitada.</p></div>}
      {step === 1 && <div className="rounded-2xl border border-dashed border-teal-300 bg-teal-50/50 p-6 text-center"><FileUp className="mx-auto size-10 text-teal-700" /><p className="mt-3 font-semibold text-slate-900">Empieza por tus documentos más confiables</p><p className="mt-1 text-sm text-slate-600">Puedes subirlos por tipo y continuar mientras CernoIA procesa la información.</p></div>}
      {step === 2 && <div className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-6 text-center"><Sparkles className="mx-auto size-10 text-indigo-700" /><p className="mt-3 font-semibold text-slate-900">La evidencia mejora la recomendación</p><p className="mt-1 text-sm leading-6 text-slate-600">La guía de cada oportunidad mostrará qué requisitos están cubiertos, cuáles faltan y qué documentos conviene preparar.</p></div>}
      <DialogFooter className="flex-col-reverse gap-2 sm:flex-row sm:justify-between"><Button variant="ghost" onClick={closeGuide}>Saltar por ahora</Button><div className="flex gap-2">{step > 0 && <Button variant="outline" onClick={() => setStep((current) => current - 1)}>Atrás</Button>}{step === 0 && <><Button variant="outline" onClick={() => goTo("settings")}>Verificar datos</Button><Button variant="outline" onClick={() => goTo("documents")}><FileUp /> Cargar documentos</Button></>}{step < 2 ? <Button onClick={() => setStep((current) => current + 1)}>Continuar <ArrowRight /></Button> : <Button onClick={() => goTo("opportunities")}>Ver oportunidades <ArrowRight /></Button>}</div></DialogFooter>
    </DialogContent></Dialog>
  </>;
}
