"use client";
import {useState,useEffect,useCallback} from 'react';
import {apiFetch} from '@/lib/api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
type Idea={id:string;title:string;brand:string;status:string;scheduled_at:string;error:string|null;storyboard:{description:string;scenes:Array<{voice:string;screen_text:string}>;sources:string[]}};
type Factory={enabled:boolean;voice:string;model:string;geminiConfigured:boolean;pexelsConfigured:boolean;freeTierConfirmed:boolean;nextRun:string;heartbeat:string;status:string;error:string|null;freeBytes:number;usedBytes:number;ideas:Idea[]};
const states:Record<string,string>={pending:'En cola · producción automática',rendering:'Produciendo',rendered:'Video listo',held:'Requiere verificación',failed:'Producción fallida'};
const date=(s:string)=>new Date(s).toLocaleString('es-CO',{timeZone:'America/Bogota',dateStyle:'short',timeStyle:'short'});
export function FactoryPanel(){
 const [data,setData]=useState<Factory|null>(null),[busy,setBusy]=useState(false),[gemini,setGemini]=useState(''),[pexels,setPexels]=useState(''),[voice,setVoice]=useState('ef_dora'),[free,setFree]=useState(false),[confirm,setConfirm]=useState<Idea|null>(null),[error,setError]=useState('');
 const load=useCallback(async(initial=false)=>{try{const d=await apiFetch<Factory>('/platform/youtube/factory');setData(d);setError('');if(initial){setVoice(d.voice);setFree(d.freeTierConfirmed);}}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la fábrica.');}},[]);
 useEffect(()=>{void load(true);const t=setInterval(()=>void load(),20000);return()=>clearInterval(t);},[load]);
 async function save(enabled:boolean){setBusy(true);try{await apiFetch('/platform/youtube/factory',{method:'PUT',body:JSON.stringify({enabled,voice,freeTierConfirmed:free,geminiKey:gemini,pexelsKey:pexels})});setGemini('');setPexels('');await load();toast.success(enabled?'Producción automática configurada.':'Producción pausada. El video en curso terminará.');}catch(e){toast.error(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 return <div className="space-y-4">{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{data&&<>
  <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Fábrica de contenido</p><h2 className="mt-1 text-xl font-semibold">Un video cada 3 horas</h2><p className="mt-2 text-sm text-slate-600">Energética Nika + CernoIA · voz, recursos de Pexels, subtítulos y miniatura.</p></div><Button disabled={busy} variant="outline" onClick={()=>void save(!data.enabled)}>{data.enabled?'Pausar producción':'Activar producción'}</Button></div>
  <div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-xl bg-teal-50 p-3"><p className="font-semibold">{data.enabled?'Automatización activada':'En pausa'}</p><p className="mt-1 text-xs">{data.status}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="font-semibold">Próxima producción</p><p className="mt-1">{date(data.nextRun)} · Colombia</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="font-semibold">Espacio del servidor</p><p className="mt-1">{(data.freeBytes/1024**3).toFixed(1)} GB libres · {(data.usedBytes/1024**2).toFixed(0)} MB en videos</p></div></div>
  {data.error&&<p role="alert" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{data.error}</p>}
  <p className="mt-4 text-xs leading-5 text-slate-500">Puedes descartar un guion antes de su turno. Si no lo descartas, se produce automáticamente. La publicación en YouTube sigue siendo manual. Un solo render simultáneo; la producción espera si quedan menos de 3 GB libres o la biblioteca llega a 2 GB. Los temporales se limpian al terminar.</p>
  <details className="mt-4 border-t pt-4"><summary className="cursor-pointer font-medium">Voz y servicios gratuitos</summary><div className="mt-4 grid gap-5 lg:grid-cols-2"><div className="space-y-3"><label className="block text-sm">Voz española<select className="mt-2 w-full rounded-lg border p-2" value={voice} onChange={e=>setVoice(e.target.value)}><option value="ef_dora">Dora · Kokoro local</option><option value="em_alex">Alex · Kokoro local</option></select></label><audio key={voice} controls preload="none" className="w-full" src={`/api/platform/youtube/factory/voice/${voice}`}/><p className="text-xs text-slate-500">Escucha la muestra y elige. El cambio se aplicará a los próximos videos. No consume API de voz.</p></div><div className="space-y-3"><p className="text-sm">Gemini: {data.geminiConfigured?'clave guardada':'sin configurar'} · Pexels: {data.pexelsConfigured?'clave guardada':'sin configurar'}</p><Input type="password" autoComplete="new-password" aria-label="Clave Gemini" placeholder="Nueva clave Gemini (opcional)" value={gemini} onChange={e=>setGemini(e.target.value)}/><Input type="password" autoComplete="new-password" aria-label="Clave Pexels" placeholder="Nueva clave Pexels (opcional)" value={pexels} onChange={e=>setPexels(e.target.value)}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/><span>Confirmo que el proyecto de Gemini está en Free tier, sin facturación habilitada.</span></label><p className="text-xs leading-5 text-slate-500">Obtén Gemini en <a className="underline" href="https://aistudio.google.com/api-keys" target="_blank" rel="noreferrer">AI Studio → Crear clave</a>, sin activar facturación. Para Pexels: <a className="underline" href="https://www.pexels.com/api/" target="_blank" rel="noreferrer">iniciar sesión → solicitar API key gratuita</a>. Guarda las claves aquí, no por chat.</p><Button disabled={busy} onClick={()=>void save(data.enabled)}>Guardar configuración</Button></div></div></details>
  </div>
  <div className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Próximas ideas y guiones</h2><span className="text-xs text-slate-500">Selección mediante Gemini</span></div>{!data.ideas.length&&<p className="mt-4 text-sm text-slate-500">La cola se llenará automáticamente cuando Gemini esté configurado y confirmado como gratuito.</p>}<div className="mt-4 space-y-3">{data.ideas.map(idea=><details key={idea.id} className="rounded-xl border p-4"><summary className="cursor-pointer"><span className="font-medium">{idea.title}</span><span className="mt-1 block text-xs text-slate-500">{idea.brand==='nika'?'Energética Nika':'CernoIA'} · {states[idea.status]||idea.status} · {date(idea.scheduled_at)}</span></summary><div className="mt-4 space-y-3"><p className="text-sm text-slate-600">{idea.storyboard.description}</p>{idea.storyboard.scenes.map((scene,i)=><div key={i} className="border-l-2 border-teal-200 pl-3"><p className="text-xs font-semibold text-teal-700">Escena {i+1} · {scene.screen_text}</p><p className="mt-1 text-sm leading-6">{scene.voice}</p></div>)}{idea.error&&<p className="rounded bg-amber-50 p-3 text-sm">{idea.error}</p>}<p className="text-xs text-slate-500">Fuentes propuestas por la IA: deben comprobarse antes de publicar.</p>{idea.storyboard.sources?.map((url,i)=><a key={i} className="block break-all text-xs text-teal-700 underline" href={url.startsWith('https://')?url:undefined} target="_blank" rel="noreferrer">{url}</a>)}{['pending','held','failed'].includes(idea.status)&&<Button variant="outline" className="text-red-700" disabled={busy} onClick={()=>setConfirm(idea)}>Descartar idea</Button>}</div></details>)}</div></div>
  {confirm&&<div role="dialog" aria-modal="true" aria-label="Descartar idea" className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-w-md rounded-2xl bg-white p-6"><h3 className="text-lg font-semibold">Descartar esta idea</h3><p className="mt-3 text-sm">«{confirm.title}» saldrá de la cola y no se producirá.</p><div className="mt-5 flex gap-3"><Button variant="outline" onClick={()=>setConfirm(null)}>Conservar</Button><Button disabled={busy} onClick={async()=>{setBusy(true);try{await apiFetch(`/platform/youtube/ideas/${confirm.id}`,{method:'DELETE'});setConfirm(null);await load();toast.success('Idea descartada.');}catch(e){toast.error(e instanceof Error?e.message:'No se pudo descartar.');}finally{setBusy(false);}}}>Descartar idea</Button></div></div></div>}
 </>}</div>;
}
