import "./cernoia-experience.css";
import { ExperienceHeader, ExperienceHome } from "./cernoia-experience";
import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, Target, FileCheck2, MessageCircle, FilePenLine, MapPinned, Bell, Check, ArrowUpRight } from "lucide-react";
import { BrandLockup } from "@/app/components/brand-mark";

const links = [["/licitaciones-secop", "Licitaciones SECOP"], ["/capacidades", "Capacidades"], ["/como-funciona", "Cómo funciona"], ["/articulos", "Guías"], ["/planes", "Planes"], ["/preguntas-frecuentes", "Preguntas frecuentes"]];
export function PublicSite({ children, experienceHeader = false }: { children: ReactNode; experienceHeader?: boolean }) {
  return <div className={`${experienceHeader ? "ce-public " : ""}min-h-screen bg-[#f4f7f6] text-[#102d35]`}>
    <Link href="#contenido" className="sr-only focus:not-sr-only focus:block focus:bg-teal-100 focus:p-4">Saltar al contenido</Link>
    {experienceHeader ? <ExperienceHeader /> : <header className="border-b border-[#dce4e3] bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-6 py-5 lg:px-10">
      <Link href="/" aria-label="CernoIA, inicio"><BrandLockup className="text-[#082d38] [&_.brand-mark]:text-teal-700" /></Link>
      <nav aria-label="Navegación principal" className="order-3 flex w-full flex-wrap gap-x-6 gap-y-3 text-sm font-medium lg:order-none lg:w-auto">{links.map(([href, label]) => <Link className="hover:text-teal-700 hover:underline underline-offset-4" key={href} href={href}>{label}</Link>)}</nav>
      <Link href="/acceso" className="rounded-full bg-[#0b5963] px-5 py-3 text-sm font-semibold text-white hover:bg-[#084852]">Ingresar <ArrowUpRight className="ml-1 inline size-4" /></Link>
    </div></header>}
    <main id="contenido">{children}</main>
    <footer className="border-t border-white/10 bg-[#061f28] text-slate-300"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-12 md:grid-cols-2 lg:px-10"><div><BrandLockup className="text-white [&_.brand-mark]:text-teal-300" /><p className="mt-5 max-w-md text-sm leading-6">Inteligencia de mercados públicos para equipos que quieren tomar decisiones con contexto.</p><p className="mt-4 max-w-md text-xs leading-5 text-slate-400">CernoIA es una plataforma privada e independiente. No pertenece a SECOP ni a Colombia Compra Eficiente.</p><div className="mt-5 text-xs leading-6 text-slate-400"><p>Desarrollado y operado por Energética Nika S.A.S. · NIT 902050074-0 · Tuluá, Valle del Cauca</p><p><a className="text-teal-300 hover:underline" href="https://wa.me/573207830189">WhatsApp +57 320 783 0189</a> · <a className="text-teal-300 hover:underline" href="mailto:director@energeticanika.com">director@energeticanika.com</a></p><p>Todos los derechos reservados.</p></div></div><nav aria-label="Enlaces del pie de página" className="flex flex-wrap content-start gap-x-8 gap-y-5 text-sm">{links.map(([href, label]) => <Link key={href} href={href} className="hover:text-teal-300">{label}</Link>)}<Link href="/acceso" className="hover:text-teal-300">Espacio de trabajo</Link></nav></div></footer>
  </div>;
}
export function PageHeading({ label, title, children, aside }: { label: string; title: string; children: ReactNode; aside?: { kicker: string; title: string; text: string } }) {
  const defaults: Record<string, { kicker: string; title: string; text: string }> = { "Guías CernoIA": { kicker: "Biblioteca para tu equipo", title: "Del dato publicado a una revisión útil.", text: "Aprende a leer oportunidades, requisitos y documentos antes de decidir." }, Capacidades: { kicker: "Dentro de la plataforma", title: "Oportunidad, requisito y evidencia.", text: "Explora el mercado y entiende qué debe comprobar tu empresa." }, "Cómo funciona": { kicker: "El recorrido CernoIA", title: "Configura, analiza y prepara.", text: "Cada etapa deja información clara para que tu equipo pueda revisar." }, Planes: { kicker: "Acceso por organización", title: "Elige el espacio que necesita tu equipo.", text: "Consulta disponibilidad, activa tu plan y gestiona cada renovación desde tu cuenta." } };
  const panel = aside ?? defaults[label] ?? { kicker: `CernoIA / ${label}`, title: "El contexto correcto cambia la siguiente decisión.", text: "Tu equipo conserva el control." };
  return <section className="public-page-hero overflow-hidden bg-[#061f28] text-white"><div className="mx-auto grid max-w-7xl items-end gap-12 px-6 py-16 lg:grid-cols-[1.15fr_.85fr] lg:px-10 lg:py-24"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-teal-300">{label}</p><h1 className="mt-6 max-w-4xl text-4xl font-semibold leading-[1.04] tracking-[-.04em] md:text-6xl">{title}</h1><div className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">{children}</div></div><div className="relative rounded-3xl border border-white/15 bg-white/[.04] p-6 shadow-2xl md:p-8"><div className="public-page-hero-grid" /><p className="relative text-xs font-semibold uppercase tracking-[.2em] text-teal-300">{panel.kicker}</p><p className="relative mt-6 text-2xl font-medium leading-tight">{panel.title}</p><div className="relative mt-8 flex items-start gap-3 text-sm leading-6 text-teal-100"><span className="mt-2 size-2 shrink-0 rounded-full bg-teal-300 shadow-[0_0_0_6px_rgba(94,234,212,.12)]" /> {panel.text}</div></div></div></section>;
}
export const capabilities = [
  { icon: Target, title: "Oportunidades con contexto", text: "Explora procesos de contratación pública y priorízalos según el perfil, las capacidades y los intereses de tu empresa." },
  { icon: MapPinned, title: "Una visión de tu mercado", text: "Consulta el mapa de contratación por territorio y entidad para orientar tu estrategia comercial." },
  { icon: FileCheck2, title: "Documentos bajo control", text: "Organiza tus documentos empresariales, extrae contenido de PDF y revisa su cobertura frente a los requisitos de cada proceso." },
  { icon: MessageCircle, title: "Un asistente para tu equipo", text: "Conversa con CernoIA sobre tu contexto empresarial y utiliza sus respuestas como apoyo para el análisis y la revisión." },
  { icon: FilePenLine, title: "Propuestas y autollenado", text: "Prepara borradores y completa plantillas con datos verificados. Revisa el resultado antes de descargarlo y presentarlo." },
  { icon: Bell, title: "Seguimiento y alertas", text: "Reúne alertas y tareas de seguimiento en tu espacio de trabajo. Los envíos por correo o WhatsApp requieren configurar y verificar cada canal." },
];
export function CapabilityGrid() {
  return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(({ icon: Icon, title, text }, index) => <article key={title} className="public-feature-card rounded-2xl border border-[#dce4e3] bg-white p-7"><div className="flex items-center justify-between"><span className="flex size-11 items-center justify-center rounded-xl bg-[#e5f5f0] text-teal-700"><Icon className="size-6" /></span><span className="font-mono text-xs text-slate-400">0{index + 1}</span></div><h3 className="mt-6 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></article>)}</div>;
}
export function ClosingCTA() { return <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="flex flex-wrap items-center justify-between gap-8 rounded-3xl bg-[#dff1e9] p-8 md:p-12"><div><h2 className="text-3xl font-semibold tracking-tight">Convierte oportunidades en una decisión informada.</h2><p className="mt-3 text-slate-600">Conoce los planes de CernoIA y solicita la membresía para tu empresa.</p></div><Link href="/planes" className="inline-flex items-center gap-3 rounded-full bg-[#0b5963] px-6 py-4 font-semibold text-white hover:bg-[#084852]">Ver planes y membresía <ArrowRight className="size-5" /></Link></div></section>; }
export function PublicHome() { return <PublicSite experienceHeader><ExperienceHome /></PublicSite>; }
