"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Archive,CheckCircle2,Eye,FileCheck2,Files,Loader2,RefreshCw,Sparkles} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {DocumentViewer,type DocumentViewerTarget} from "./document-viewer";
import {apiFetch,downloadBidZip,type OpportunitySourceDocument} from "@/lib/api";
import {bidDocumentName} from "@/lib/bids";
import type {BidWorkspace,BidTemplate,BidMatrixDocument,AnnexCatalog} from "@/lib/bids";
import {formatDate} from "@/lib/format";
import {AnnexWorkspace} from "./annex-workspace";
const roles:Record<string,string>={informative:"Informativo",fillable:"Requiere diligenciamiento",mixed:"Informativo y diligenciable",unknown:"Clasificación pendiente",not_required:"Excluido por tu equipo"};
const issues:Record<string,string>={required_value_missing:"Falta un dato",signature_missing:"Falta aplicar la firma",no_fillable_fields:"Identifica los campos del formato",invalid_position:"Revisa la posición del campo",value_not_accepted:"Valor no aceptado",review_official_annex:"Revisa el formato oficial",review_overlay_position:"Comprueba la posición del texto",formula_cell_protected:"La celda contiene una fórmula",value_overflows_field:"El texto no cabe en el campo"};
export function BidLifecycle({processId,canEdit,hasAnalysis,sourceDocuments=[],onContinued,catalog,catalogLoading,onRefreshCatalog}:{processId:string;canEdit:boolean;hasAnalysis:boolean;sourceDocuments?:OpportunitySourceDocument[];onContinued?:()=>void;catalog?:AnnexCatalog|null;catalogLoading?:boolean;onRefreshCatalog?:()=>void}){
 const [data,setData]=useState<BidWorkspace|null>(null),[error,setError]=useState("");const [busy,setBusy]=useState("");const [selected,setSelected]=useState<Record<string,string>>({});const [confirmed,setConfirmed]=useState(false);const [preview,setPreview]=useState<{document:BidTemplate;pages:number;hash:string;source_hash:string}|null>(null);const [imageLoaded,setImageLoaded]=useState(false),[reviewConfirmed,setReviewConfirmed]=useState(false);const [loading,setLoading]=useState(true);const fingerprint=useRef("");const [sourceViewer,setSourceViewer]=useState<DocumentViewerTarget|null>(null);
 const load=useCallback(async()=>{try{const value=await apiFetch<BidWorkspace>(`/bids/processes/${processId}`);setData(value);setError("");const next=JSON.stringify([value.matrix?.revision_hash,value.templates?.map(t=>[t.generated_id,t.approved]),value.matrix?.documents.map(d=>[d.id,d.effective_role])]);if(next!==fingerprint.current){setConfirmed(false);fingerprint.current=next;}}catch(e){setError(e instanceof Error?e.message:"No se pudo consultar la preparación.");}finally{setLoading(false);}},[processId]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load();},10000);return()=>clearInterval(timer);},[load]);
 async function action(label:string,work:()=>Promise<void>){setBusy(label);try{await work();await load();}catch(e){toast.error(e instanceof Error?e.message:"No fue posible completar esta acción.");}finally{setBusy("");}}
 async function start(){await action("Preparando espacio…",async()=>{const result=await apiFetch<{reused:boolean}>(`/bids/processes/${processId}/continue`,{method:"POST",body:"{}"});toast.success(result.reused?"Usaremos la matriz pública guardada del proceso.":"La clasificación y matriz pública quedaron en preparación.");onContinued?.();});}
 async function autofill(){await action("Importando formatos…",async()=>{const imported=await apiFetch<{templates:Array<{id:string}>}>(`/bids/processes/${processId}/import-forms`,{method:"POST",body:"{}"});const current=await apiFetch<BidWorkspace>(`/bids/processes/${processId}`);let count=0;for(const t of current.templates??[]){if(!imported.templates.some(i=>i.id===t.id)||t.generated_id&&t.template_version_id===t.version_id)continue;setBusy(`Diligenciando ${++count} de ${imported.templates.length}…`);await apiFetch(`/templates/${t.id}/generate`,{method:"POST",body:JSON.stringify({process_id:processId})});}toast.success("Formatos preparados. Revisa los campos pendientes y cada vista previa.");});}
 async function openPreview(t:BidTemplate){if(!t.generated_id)return;await action("Generando vista previa…",async()=>{const p=await apiFetch<{pages:number;hash:string;source_hash:string}>(`/bids/documents/${t.generated_id}/preview`,{method:"POST",body:"{}"});setImageLoaded(false);setReviewConfirmed(false);setPreview({document:t,...p});});}
 if(loading)return <div className="flex items-center gap-2 rounded-xl border p-5 text-sm"><Loader2 className="size-4 animate-spin"/>Cargando preparación de oferta…</div>;
 if(error)return <div className="rounded-xl border border-rose-200 p-5"><p className="text-sm text-rose-800">{error}</p><Button className="mt-3" variant="outline" onClick={()=>void load()}>Reintentar</Button></div>;
 const canStart=data?.can_start??hasAnalysis;
 if(!data?.workspace)return <section className="space-y-4 rounded-2xl border border-teal-200 bg-teal-50 p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><Files className="size-5"/>Del análisis a la oferta</h3><p className="text-sm leading-6 text-slate-600">Al continuar, CernoIA clasifica los documentos públicos, conserva la matriz informativa del proceso y prepara los formatos para autollenado. Tu empresa revisa los archivos antes de descargar el ZIP.</p>{!canStart&&<p className="text-sm text-amber-800">Completa el análisis con IA para iniciar este paso.</p>}{canEdit&&<Button disabled={!canStart||!!busy} onClick={()=>void start()} className="bg-[#0b5963] hover:bg-[#084852]">{busy?<Loader2 className="animate-spin"/>:<CheckCircle2/>}Empezar diligenciamiento</Button>}</section>;
 const docs=data.matrix?.documents??[],templates=data.templates??[],blockers=data.blockers??[];const approved=templates.filter(t=>t.approved).length;
 return <section className="space-y-5">
  <div className="rounded-2xl bg-[#082f38] p-5 text-white"><h3 className="text-xl font-semibold">Preparación de tu oferta</h3><p className="mt-2 text-sm leading-6 text-slate-200">La matriz pública se comparte por versión. Los formatos diligenciados y soportes de tu empresa son privados.</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{[["1. Matriz pública",`${docs.filter(d=>d.status==="ready").length}/${docs.length} documentos`],["2. Autollenado",`${docs.filter(d=>["fillable","mixed"].includes(d.effective_role)).length} formatos`],["3. Revisión",`${approved}/${templates.length} aprobados`],["4. Descarga","Paquete ZIP"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/15 bg-white/5 p-3"><p className="font-semibold text-teal-200">{a}</p><p className="mt-1 text-xs text-slate-200">{b}</p></div>)}</div></div>
  <AnnexWorkspace catalog={catalog} catalogLoading={catalogLoading} onRefreshCatalog={onRefreshCatalog} processId={processId} documents={sourceDocuments} canEdit={canEdit&&!busy} templateIds={templates.map(t=>t.id)} onChange={load}/>
  <details className="rounded-xl border"><summary className="cursor-pointer p-4 text-sm font-semibold">Análisis y clasificación de los documentos</summary><div className="space-y-3 rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-semibold">Matriz informativa del proceso</h4>{canEdit&&<Button variant="outline" size="sm" disabled={!!busy} onClick={()=>void action("Actualizando fuentes…",async()=>{await apiFetch(`/bids/processes/${processId}/refresh`,{method:"POST",body:"{}"});})}><RefreshCw/>Actualizar fuentes</Button>}</div><p className="text-xs leading-5 text-slate-500">{data.matrix?.status==="ready"?"Lectura guardada y reutilizable. Cada dato conserva su cita de origen.":"La lectura se realiza en segundo plano. Los resultados aparecerán aquí al completarse."}{data.matrix?.stale&&" Hay cambios en el inventario que debes actualizar."}</p>{!docs.length&&<p className="text-sm text-amber-800">Todavía no hay documentos en el inventario del proceso. Actualiza las fuentes para solicitar su sincronización.</p>}{docs.map(d=><PublicDocument key={d.id} doc={d} onPreview={()=>setSourceViewer({title:d.filename,beforeEndpoint:`/opportunities/${processId}/documents/${d.process_document_id}/preview`})} canEdit={canEdit&&!busy} onClassify={async(role,reason)=>{await apiFetch(`/bids/processes/${processId}/documents/${d.id}`,{method:"PATCH",body:JSON.stringify({role,reason})});await load();}}/>)}</div></details>
  {canEdit&&<Button onClick={()=>void autofill()} disabled={!!busy||!docs.some(d=>d.status==="ready"&&["fillable","mixed"].includes(d.effective_role))} className="bg-[#0b5963] hover:bg-[#084852]">{busy?<Loader2 className="animate-spin"/>:<Sparkles/>}{busy||"Autollenar formatos del proceso"}</Button>}
  <div className="space-y-3 rounded-xl border bg-white p-4"><h4 className="font-semibold">Previsualizar y aprobar documentos</h4>{!templates.length&&<p className="text-sm text-slate-500">Los formatos aparecerán aquí después de importarlos o cargarlos.</p>}{templates.map(t=><article key={t.id} className="space-y-2 rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="min-w-0 flex-1 break-words text-sm font-semibold">{bidDocumentName(t.name)}</p><span className={`rounded-full px-2 py-1 text-xs ${t.approved?"bg-teal-50 text-teal-800":"bg-amber-50 text-amber-900"}`}>{t.approved?"Versión aprobada":"Revisión pendiente"}</span></div>{t.validation_issues?.length? <ul className="list-inside list-disc text-xs leading-5 text-amber-900">{t.validation_issues.map((i,n)=><li key={n}>{issues[i.code]||"Revisar campo"}: {i.field}</li>)}</ul>:null}{t.generated_id?<Button variant="outline" size="sm" disabled={!!busy} onClick={()=>void openPreview(t)}><Eye/>Ver antes y después</Button>:<p className="text-xs text-slate-500">Diligencia los campos y genera el documento.</p>}</article>)}</div>
  <div className="space-y-3 rounded-xl border bg-white p-4"><h4 className="font-semibold">Soportes empresariales para adjuntar</h4><p className="text-xs leading-5 text-slate-500">Selecciona los soportes exigidos por la matriz. Revisa su contenido, firmas y vigencias.</p>{(data.supports??[]).map(s=><label key={s.id} className="flex items-start gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" className="mt-1" disabled={!canEdit||!!busy} checked={!!selected[s.id]} onChange={e=>{setSelected(current=>{const next={...current};if(e.target.checked)next[s.id]=s.file_hash_sha256;else delete next[s.id];return next;});setConfirmed(false);}}/><span className="min-w-0 flex-1 break-words">{s.document_name}{s.expiration_date&&<span className="mt-1 block text-xs text-slate-500">Vigencia: {formatDate(s.expiration_date)}</span>}</span><a href={`/api/documents/${s.id}/file`} target="_blank" rel="noreferrer" className="text-xs font-semibold text-teal-800 underline">Revisar</a></label>)}</div>
  <div className="space-y-4 rounded-2xl border border-teal-200 bg-teal-50 p-5"><h4 className="flex items-center gap-2 font-semibold"><Archive className="size-5"/>Paquete para cargar en SECOP</h4><p className="text-sm leading-6 text-slate-600">Incluye los formularios aprobados, los soportes seleccionados y un control de los archivos. Las vistas PDF acompañan a los originales editables.</p>{!!blockers.length&&<details className="text-sm text-amber-900"><summary className="cursor-pointer font-medium">{blockers.length} pendientes antes de descargar</summary><ul className="mt-2 list-inside list-disc space-y-1">{blockers.map((b,i)=><li key={i}>{b}</li>)}</ul></details>}{canEdit&&<><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={!!blockers.length||!!busy}/><span>Revisé los documentos finales, los soportes necesarios, sus firmas y vigencias para esta oferta.</span></label><Button className="bg-[#0b5963] hover:bg-[#084852]" disabled={!!busy||!!blockers.length||!confirmed} onClick={()=>void action("Preparando ZIP…",async()=>{await downloadBidZip(processId,{matrix_revision:data.matrix?.revision_hash,support_ids:Object.keys(selected),support_hashes:selected,confirmed});toast.success("Paquete descargado.");})}><Archive/>Descargar ZIP de la oferta</Button></>}</div>
  <DocumentViewer target={preview?{title:bidDocumentName(preview.document.name),beforeEndpoint:`/template-versions/${preview.document.template_version_id||preview.document.version_id}/preview`,afterDocumentId:preview.document.generated_id!}:null} onClose={()=>setPreview(null)} onAfterLoaded={setImageLoaded} footer={preview&&canEdit?<><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={reviewConfirmed} onChange={e=>setReviewConfirmed(e.target.checked)}/><span>Revisé el contenido y la presentación de esta versión.</span></label><Button disabled={!!busy||!imageLoaded||!reviewConfirmed} onClick={()=>void action("Guardando revisión…",async()=>{await apiFetch(`/bids/documents/${preview.document.generated_id}/review`,{method:"POST",body:JSON.stringify({confirmed:true,source_hash:preview.source_hash,preview_hash:preview.hash})});setPreview(null);toast.success("Versión revisada y aprobada para el paquete.");})}><FileCheck2/>Aprobar esta versión</Button></>:null}/>
  <DocumentViewer target={sourceViewer} onClose={()=>setSourceViewer(null)}/>

 </section>;
}
function PublicDocument({doc,canEdit,onClassify,onPreview}:{doc:BidMatrixDocument;canEdit:boolean;onPreview:()=>void;onClassify:(role:string,reason:string)=>Promise<void>}){
 const [role,setRole]=useState(doc.effective_role==="unknown"?"informative":doc.effective_role),[reason,setReason]=useState(""),[saving,setSaving]=useState(false);
 return <details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm"><span className="font-medium">{doc.filename}</span><span className={`ml-2 inline-block rounded-full px-2 py-1 text-xs ${doc.effective_role==="fillable"||doc.effective_role==="mixed"?"bg-teal-50 text-teal-800":"bg-slate-100 text-slate-600"}`}>{roles[doc.effective_role]}</span><span className="ml-2 text-xs text-slate-500">{doc.status==="ready"?`${doc.facts.length} datos con cita`:doc.status==="error"?"Requiere revisión":"En preparación"}</span></summary><div className="mt-3 space-y-3">{doc.error_message&&<p className="text-sm text-amber-800">{doc.error_message}</p>}{doc.summary&&<p className="whitespace-pre-line text-sm leading-6 text-slate-600">{doc.summary}</p>}{doc.facts.map((f,i)=><div key={i} className="space-y-1 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold">{f.label}</p><p>{f.value}</p><blockquote className="border-l-2 border-teal-300 pl-3 text-xs leading-5 text-slate-500">{f.quote}</blockquote></div>)}<Button size="sm" variant="outline" onClick={onPreview}><Eye/>Ver original en el panel</Button>{doc.source_url&&<a className="text-sm text-teal-800 underline" href={doc.source_url} target="_blank" rel="noreferrer">Consultar documento público original</a>}{canEdit&&<details className="border-t pt-3"><summary className="cursor-pointer text-xs font-semibold">Corregir clasificación para mi empresa</summary><div className="mt-3 space-y-2"><select className="w-full rounded-md border p-2 text-sm" value={role} onChange={e=>setRole(e.target.value)} aria-label="Clasificación del documento">{Object.entries(roles).filter(([k])=>k!=="unknown").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className="w-full rounded-md border p-2 text-sm" aria-label="Motivo de la clasificación" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo de la corrección o exclusión"/><Button size="sm" variant="outline" disabled={saving||reason.trim().length<8} onClick={async()=>{setSaving(true);try{await onClassify(role,reason);toast.success("Clasificación guardada para tu empresa.");}catch(e){toast.error(e instanceof Error?e.message:"No fue posible guardar.");}finally{setSaving(false);}}}>Guardar clasificación</Button></div></details>}</div></details>;
}
