"use client";
import { CompanyBusinessSummary } from "./company-business-summary";
import type {BusinessSummary} from "@/lib/company-business-summary";
import { useEffect, useState } from "react";
import { Bot, FileUp, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { apiFetch, type User } from "@/lib/api";

type Fact={id:string;label:string;value:string;document_id:string;document_name:string;evidence_quote:string;evidence_status:string;interpretation:string;period:string;scope:string;conflict:boolean;expires_on:string|null};
type Matrix={business_summary?:BusinessSummary;summary:string;disclaimer:string;coverage:{documented_dimensions:number;total_dimensions:number;total_documents:number;documents_with_evidence:number;unavailable_documents:number};dimensions:{id:string;label:string;status:string;facts:Fact[]}[];conflicts:{key:string;message:string}[];declared_profile:{products_services?:string[]};documents:{id:string;name:string;status:string}[];processing:{status:string;updating:boolean;revision:number;requested_revision:number;generated_at:string|null;last_error:string|null;documents_processed:number;documents_total:number};versions:{id:string;revision:number;created_at:string}[]};
const labels:Record<string,string>={document_supported:"Con soporte documental",declared:"Declarado por la empresa",expired:"Soporte vencido",not_yet_valid:"Vigencia futura",needs_review:"Requiere revisión",missing:"Sin evidencia",conflicting:"Datos contradictorios",documented:"Con evidencia",queued:"Actualización en cola",processing:"Analizando documentos",ready:"Actualizada",empty:"Sin documentos",error:"Reintento pendiente"};
const suggestions:Record<string,string>={identity:"Cámara de Comercio y documento del representante legal.",legal:"RUT, RUP, registros y antecedentes aplicables.",services:"Certificados que describan los servicios prestados; el portafolio se conserva como información declarada.",experience:"Certificados de experiencia, actas de recibo y liquidación.",financial:"Estados financieros con período y notas.",people:"Hojas de vida, títulos y soportes de vinculación.",equipment:"Inventarios, propiedad o disponibilidad de equipos e instalaciones.",certifications:"Certificados de calidad y acreditaciones con su vigencia.",coverage:"Soportes de sedes, cobertura y operación."};
export function CompanyMatrixView({user,onDocuments,onSettings}:{user:User;onDocuments:()=>void;onSettings?:()=>void}){
 const [data,setData]=useState<Matrix|null>(null);const [error,setError]=useState("");const [requesting,setRequesting]=useState(false);
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;
  const load=async()=>{try{const result=await apiFetch<Matrix>("/company-matrix");if(active){setData(result);setError("");}}catch(e){if(active)setError(e instanceof Error?e.message:"No fue posible consultar la matriz.");}finally{if(active)timer=setTimeout(load,8000);}};
  void load();return()=>{active=false;clearTimeout(timer);};
 },[]);
 async function refresh(){setRequesting(true);try{await apiFetch("/company-matrix/refresh",{method:"POST"});setData(await apiFetch<Matrix>("/company-matrix"));toast.success("La actualización quedó en cola.");}catch(e){toast.error(e instanceof Error?e.message:"No fue posible solicitar la actualización.");}finally{setRequesting(false);}}
 return <div className="space-y-6">
  <Card><CardContent className="space-y-4 pt-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl space-y-2"><h2 className="flex items-center gap-2 text-lg font-semibold"><Bot className="size-5 text-teal-700"/>Tu empresa, a partir de sus documentos</h2><p className="text-sm text-slate-600">Los documentos son opcionales para ingresar. Cada carga, corrección o retiro actualiza automáticamente esta matriz. Aporta más soportes para conocer mejor las capacidades y la información que falta.</p></div><Button onClick={onDocuments}><FileUp className="mr-2 size-4"/>Cargar documentos</Button></div>
  {data&&<div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-sm text-slate-600"><strong>{labels[data.processing.status]??data.processing.status}</strong> · Versión {data.processing.revision}{data.processing.updating&&` · Revisando ${data.processing.documents_processed} de ${data.processing.documents_total} documentos`}{data.processing.generated_at&&` · ${new Date(data.processing.generated_at).toLocaleString("es-CO")}`}</p>{user.role!=="viewer"&&<Button variant="outline" size="sm" disabled={requesting||data.processing.updating} onClick={()=>void refresh()}><RefreshCw className={`mr-2 size-4 ${data.processing.updating?"animate-spin":""}`}/>Revisar de nuevo</Button>}</div>}
  {data?.processing.last_error&&<p className="text-sm text-amber-800">{data.processing.last_error} El sistema lo reintentará automáticamente.</p>}
  </CardContent></Card>
  {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}
  {!data&&!error&&<p className="text-sm text-slate-500">Consultando la matriz empresarial…</p>}
  {data&&<><div className="grid gap-4 sm:grid-cols-3">{[["Áreas con evidencia vigente",`${data.coverage.documented_dimensions} de ${data.coverage.total_dimensions}`],["Documentos aportados",data.coverage.total_documents],["Documentos con datos citados",data.coverage.documents_with_evidence]].map(([label,value])=><Card key={label}><CardContent className="pt-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>)}</div>
  {data.business_summary&&<CompanyBusinessSummary summary={data.business_summary} declared={data.declared_profile.products_services??[]} onSettings={onSettings}/>}
  <p className="text-sm text-slate-600">{data.summary} {data.disclaimer}</p>
  {data.dimensions.some(d=>d.facts.some(f=>f.evidence_status==="expired"))&&<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Hay soportes con fechas de vigencia registradas vencidas. Sus datos se conservan como antecedentes. Revisa las fechas y aporta documentos actualizados cuando corresponda.</p>}
  {data.coverage.unavailable_documents>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Hay {data.coverage.unavailable_documents} registros sin archivo ni texto legible.</strong> Carga sus archivos para que la IA pueda leerlos. Registrar el nombre de un documento no acredita su contenido.<ul className="mt-2 list-inside list-disc">{data.documents.filter(d=>d.status==="missing_file").map(d=><li key={d.id}>{d.name}</li>)}</ul></div>}
  {data.documents.some(d=>["unreadable","blocked"].includes(d.status))&&<div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Documentos pendientes de lectura o revisión</strong><ul className="mt-2 list-inside list-disc">{data.documents.filter(d=>["unreadable","blocked"].includes(d.status)).map(d=><li key={d.id}>{d.name}: {d.status==="blocked"?"pendiente de validación del archivo":"no se pudo extraer texto útil; revisa el archivo o carga una copia más legible"}</li>)}</ul></div>}
  {data.conflicts.length>0&&<p role="status" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Se encontraron {data.conflicts.length} posibles contradicciones. Revisa las fuentes antes de usar esos datos.</p>}
  <div className="space-y-3">{data.dimensions.map(d=><details key={d.id} className="rounded-2xl border bg-white p-5" open={d.status==="conflicting"?true:undefined}><summary className="cursor-pointer text-sm font-semibold">{d.label}<span className="ml-3 font-normal text-slate-500">{labels[d.status]} · {d.facts.length} datos</span></summary><div className="mt-4 space-y-4">{!d.facts.length&&<p className="text-sm text-slate-600">Puedes aportar: {suggestions[d.id]}</p>}{d.facts.map(f=><article key={f.id} className="space-y-2 rounded-xl bg-slate-50 p-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{f.label}{f.period?` · ${f.period}`:""}</strong><span className={f.conflict||f.evidence_status!=="document_supported"?"text-amber-800":"text-teal-800"}>{f.conflict?"Posible contradicción":labels[f.evidence_status]}</span></div><p className="break-words">{f.value}</p>{f.interpretation&&<p className="text-slate-600">Lectura de IA: {f.interpretation}</p>}<blockquote className="border-l-2 border-teal-300 pl-3 text-slate-600">“{f.evidence_quote}”</blockquote><div className="flex flex-wrap justify-between gap-2 text-xs"><a className="text-teal-800 underline" href={`/api/documents/${encodeURIComponent(f.document_id)}/file`} target="_blank" rel="noreferrer">Fuente: {f.document_name}</a>{f.expires_on&&<span>Vigencia registrada: {f.expires_on}</span>}</div></article>)}</div></details>)}</div>
  {!data.business_summary&&!!data.declared_profile.products_services?.length&&<Card><CardContent className="pt-5"><h3 className="text-sm font-semibold">Servicios declarados en tu perfil</h3><p className="mt-2 text-sm text-slate-600">{data.declared_profile.products_services.join(" · ")}</p><p className="mt-2 text-xs text-slate-500">Se conservan separados de las capacidades respaldadas por documentos.</p></CardContent></Card>}
  {!!data.versions.length&&<details className="text-sm text-slate-600"><summary className="cursor-pointer">Historial de actualizaciones</summary><ul className="mt-3 space-y-2">{data.versions.map(v=><li key={v.id}>Versión {v.revision} · {new Date(v.created_at).toLocaleString("es-CO")}</li>)}</ul></details>}</>}
 </div>;
}
