"use client";
import {useEffect,useState,type ReactNode} from "react";
import {ArrowLeft,ChevronLeft,ChevronRight,Download,Eye,FileArchive,Loader2,Sparkles} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {apiFetch} from "@/lib/api";
export type DocumentViewerTarget={title:string;beforeEndpoint:string;afterDocumentId?:string};
type Preview={preview_notice?:string;id?:string;filename?:string;pages:number;hash:string;source_hash:string;pdf_url:string;page_url:string;original_url?:string;entries?:Array<{id:string;filename:string;name:string;bytes:number;supported:boolean}>};
export function DocumentViewer({target,onClose,canImport=false,onImported,footer,onAfterLoaded}:{target:DocumentViewerTarget|null;onClose:()=>void;canImport?:boolean;onImported?:(id:string)=>Promise<void>;footer?:ReactNode;onAfterLoaded?:(loaded:boolean)=>void}){
 const [before,setBefore]=useState<Preview|null>(null),[after,setAfter]=useState<Preview|null>(null),[parents,setParents]=useState<Preview[]>([]);
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mobile,setMobile]=useState("before");
 useEffect(()=>{if(!target)return;let alive=true;setBefore(null);setAfter(null);setParents([]);setError("");setLoading(true);setMobile("before");
  void(async()=>{try{const original=await apiFetch<Preview>(target.beforeEndpoint,{method:"POST",body:"{}"});if(!alive)return;setBefore(original);
   if(target.afterDocumentId){const generated=await apiFetch<Preview>(`/bids/documents/${target.afterDocumentId}/preview`,{method:"POST",body:"{}"});if(alive)setAfter({...generated,page_url:`/api/bids/documents/${target.afterDocumentId}/pages/{page}`});}
  }catch(e){if(alive)setError(e instanceof Error?e.message:"No se pudo abrir el documento.");}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};
 },[target?.beforeEndpoint,target?.afterDocumentId]);
 async function openEntry(entryId:string){if(!before?.id)return;setBusy(true);setError("");try{const value=await apiFetch<Preview>(`/source-previews/${before.id}/entries/${entryId}/preview`,{method:"POST",body:"{}"});setParents([...parents,before]);setBefore(value);}catch(e){setError(e instanceof Error?e.message:"No se pudo abrir el archivo del ZIP.");}finally{setBusy(false);}}
 async function importFile(){if(!before?.id)return;setBusy(true);try{const result=await apiFetch<{template:{id:string}}>(`/source-previews/${before.id}/import`,{method:"POST",body:"{}"});await onImported?.(result.template.id);onClose();toast.success("Original preparado. Ya puedes revisar los campos y diligenciarlo.");}catch(e){toast.error(e instanceof Error?e.message:"No se pudo preparar el archivo.");}finally{setBusy(false);}}
 return <Dialog open={!!target} onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="flex max-h-[95dvh] w-[calc(100%-1rem)] flex-col overflow-y-auto sm:max-w-[min(96vw,80rem)]"><DialogHeader><DialogTitle>{target?.afterDocumentId?"Comparar original y documento diligenciado":"Ver documento original"}</DialogTitle><DialogDescription className="break-words">{target?.title}</DialogDescription></DialogHeader>
  {loading&&<p role="status" className="flex items-center gap-2 p-4 text-sm"><Loader2 className="size-4 animate-spin"/>Preparando vista del documento…</p>}
  {error&&<p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}
  {parents.length>0&&<Button size="sm" variant="outline" className="self-start" onClick={()=>{setBefore(parents.at(-1)!);setParents(parents.slice(0,-1));setError("");}}><ArrowLeft/>Volver al ZIP</Button>}
  {before?.entries?.length? <div className="space-y-2"><p className="text-sm text-slate-600"><FileArchive className="mr-2 inline size-4"/>{before.entries.length} archivos dentro del ZIP. Abre el anexo que necesites.</p>{before.entries.map(entry=><div key={entry.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-3"><span className="min-w-0 flex-1 break-words text-sm">{entry.filename}</span><Button size="sm" variant="outline" disabled={busy||!entry.supported} onClick={()=>void openEntry(entry.id)}><Eye/>{entry.supported?"Abrir anexo":"Formato no compatible"}</Button></div>)}{before.original_url&&<a href={before.original_url} className="inline-flex items-center gap-2 text-sm text-teal-800 underline"><Download className="size-4"/>Descargar ZIP original</a>}</div>:before&&<>
   {before.preview_notice&&<p className="text-xs text-slate-600">{before.preview_notice}</p>}
   {after&&<div className="flex gap-2 md:hidden"><Button size="sm" variant={mobile==="before"?"default":"outline"} onClick={()=>setMobile("before")}>Original</Button><Button size="sm" variant={mobile==="after"?"default":"outline"} onClick={()=>setMobile("after")}>Diligenciado</Button></div>}
   <div className={`grid min-w-0 gap-4 ${after?"md:grid-cols-2":""}`}><div className={after&&mobile!=="before"?"hidden md:block":""}><DocumentPages key={before.hash||before.id} preview={before} label="Original (antes)"/></div>{after&&<div className={mobile!=="after"?"hidden md:block":""}><DocumentPages key={after.hash} preview={after} label="Diligenciado (después)" onLoaded={onAfterLoaded}/></div>}</div>
   {canImport&&!after&&before.id&&<Button className="self-start bg-[#0b5963] hover:bg-[#084852]" disabled={busy||loading} onClick={()=>void importFile()}>{busy?<Loader2 className="animate-spin"/>:<Sparkles/>}Empezar diligenciamiento de este archivo</Button>}
  </>}
  {footer}
 </DialogContent></Dialog>;
}
function DocumentPages({preview,label,onLoaded}:{preview:Preview;label:string;onLoaded?:(loaded:boolean)=>void}){
 const [page,setPage]=useState(1),[zoom,setZoom]=useState(100),[failed,setFailed]=useState(false);
 function change(next:number){setPage(next);setFailed(false);onLoaded?.(false);}
 return <section aria-label={label} className="min-w-0 space-y-2"><h4 className="font-semibold">{label}</h4><div className="flex flex-wrap items-center justify-between gap-2"><Button aria-label={`Página anterior: ${label}`} size="icon-sm" variant="outline" disabled={page<=1} onClick={()=>change(page-1)}><ChevronLeft/></Button><span className="text-xs">Página {page} de {preview.pages}</span><Button aria-label={`Página siguiente: ${label}`} size="icon-sm" variant="outline" disabled={page>=preview.pages} onClick={()=>change(page+1)}><ChevronRight/></Button><select aria-label={`Zoom: ${label}`} className="rounded-md border p-1 text-xs" value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={100}>Ajustar</option><option value={150}>150 %</option><option value={200}>200 %</option></select></div><div className="max-h-[62dvh] min-h-48 overflow-auto rounded-lg border bg-slate-100 p-2">{failed&&<p role="alert" className="text-sm text-amber-900">No se pudo cargar esta página. Vuelve a abrir el documento.</p>}<img src={`${preview.page_url.replace('{page}',String(page))}?v=${preview.hash}`} alt={`Página ${page}: ${label}`} style={{width:`${zoom}%`,maxWidth:"none"}} className="mx-auto h-auto" onLoad={()=>{setFailed(false);onLoaded?.(true);}} onError={()=>{setFailed(true);onLoaded?.(false);}}/></div><div className="flex flex-wrap gap-3 text-xs"><a className="text-teal-800 underline" href={preview.pdf_url} target="_blank" rel="noreferrer">Abrir PDF completo</a>{preview.original_url&&<a className="text-teal-800 underline" href={preview.original_url}>Descargar archivo original</a>}</div></section>;
}
