"use client";
import {useCallback,useEffect,useRef,useState} from 'react';import {FileSearch,Loader2} from 'lucide-react';import {Button} from '@/components/ui/button';import {apiFetch} from '@/lib/api';
type Preparation={status:string;documents_total:number;documents_read:number;last_error:string|null;analysis_id:string|null;document_errors:Array<{name:string;message:string}>};
const labels:Record<string,string>={queued:'Consultando el inventario oficial',reading:'Leyendo documentos y extrayendo requisitos',analyzing:'Comparando con la matriz empresarial',ready:'Lectura y análisis comparativo terminados',incomplete:'Hay documentos que requieren revisión',error:'No se pudo terminar la preparación'};
export function ProcessPreparationPanel({processId,canRun,onUpdated}:{processId:string;canRun:boolean;onUpdated:()=>void}){
 const [job,setJob]=useState<Preparation|null>(null),[sending,setSending]=useState(false),[error,setError]=useState('');const notified=useRef('');
 const load=useCallback(async()=>{try{const r=await apiFetch<{preparation:Preparation|null}>(`/opportunities/${processId}/preparation`);setJob(r.preparation);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo consultar el avance.');}},[processId]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},5000);return()=>clearInterval(timer);},[load]);
 const signature=job?`${job.status}:${job.documents_total}:${job.documents_read}`:'';
 useEffect(()=>{if(signature&&signature!==notified.current){notified.current=signature;onUpdated();}},[signature,onUpdated]);
 const busy=sending||!!job&&['queued','reading','analyzing'].includes(job.status);
 return <section className="space-y-3 rounded-xl border border-teal-200 bg-teal-50/60 p-4" aria-label="Documentos y análisis del proceso"><h3 className="font-semibold text-teal-950">Documentos del proceso y comparación con tu empresa</h3><p className="text-sm leading-6 text-slate-600">Trae los pliegos, estudios y anexos disponibles en SECOP. La IA lee los archivos, extrae requisitos y después los contrasta con tu matriz empresarial. Si falta un archivo o una lectura, el sistema lo mostrará.</p>{canRun&&<Button variant="outline" disabled={busy} onClick={async()=>{setSending(true);try{await apiFetch(`/opportunities/${processId}/preparation`,{method:'POST',body:'{}'});await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar la preparación.');}finally{setSending(false);}}}>{busy?<Loader2 className="animate-spin"/>:<FileSearch/>}{busy?'Procesamiento en curso':job?.status==='ready'?'Actualizar documentos y reanalizar':'Traer documentos y analizar con IA'}</Button>}{job&&<div role="status" className="text-sm"><p className="font-medium">{labels[job.status]??job.status}</p><p className="mt-1">{job.documents_read??0} de {job.documents_total??0} archivos del inventario leídos. Los ZIP incluyen sus anexos internos.</p>{job.last_error&&<p className="mt-2 text-amber-900">{job.last_error}</p>}{job.document_errors?.map(d=><p className="mt-2 text-amber-900" key={d.name}>{d.name}: {d.message}</p>)}</div>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<p className="text-xs text-slate-500">El inventario corresponde a datos abiertos de SECOP; verifica posibles adendas aún no publicadas en esa fuente. El análisis conserva citas y requiere revisión humana.</p></section>;
}
