import {Router} from 'express';import rateLimit from 'express-rate-limit';import {ZipArchive} from 'archiver';
import {query} from '../db.js';import {requireAuth,requireRole} from '../middleware/auth.js';import {requireEntitlement} from '../middleware/subscription.js';import {writeAudit} from '../audit.js';
import {ensurePublicMatrix} from '../services/process-knowledge.js';import {assertOpportunityAccess,readBidWorkspace,importPublicTemplate} from '../services/bid-workspace.js';
import {blockingIssues,zipName,hash} from '../services/process-knowledge-rules.js';
import {ensureDocumentPreview,previewPage} from '../services/document-preview.js';import {readStoredDocument,fileSha256} from '../services/document-storage.js';import {runWorkflow} from '../services/n8n.js';
export const bidsRouter=Router();bidsRouter.use(requireAuth,requireEntitlement('document_automation'));
const previewLimit=rateLimit({windowMs:60000,limit:120,keyGenerator:req=>req.user.organization_id,standardHeaders:true,legacyHeaders:false});
const edit=requireRole('owner','admin','analyst');const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const limit=rateLimit({windowMs:60000,limit:20,keyGenerator:req=>req.user.organization_id,standardHeaders:true,legacyHeaders:false});
bidsRouter.param('processId',async(req,res,next,id)=>{try{if(!uuid.test(id))return res.status(400).json({error:'Proceso no válido.'});req.bidProcess=await assertOpportunityAccess(req.user.organization_id,id);next();}catch(e){next(e);}});
bidsRouter.param('documentId',async(req,res,next,id)=>{try{if(!uuid.test(id))return res.status(400).json({error:'Documento no válido.'});const row=(await query(`SELECT g.*,t.name,t.current_version,v.version_number FROM saas.generated_template_documents g JOIN saas.document_templates t ON t.id=g.template_id JOIN saas.document_template_versions v ON v.id=g.template_version_id WHERE g.id=$1 AND g.organization_id=$2 AND g.status IN ('ready','needs_review')`,[id,req.user.organization_id])).rows[0];if(!row)return res.status(404).json({error:'Documento generado no encontrado.'});req.bidDocument=row;next();}catch(e){next(e);}});
bidsRouter.get('/processes/:processId',async(req,res,next)=>{try{res.json(await readBidWorkspace(req.user.organization_id,req.params.processId));}catch(e){next(e);}});
bidsRouter.post('/processes/:processId/continue',edit,limit,async(req,res,next)=>{try{
 const success=await query("SELECT 1 FROM saas.opportunity_ai_analyses WHERE organization_id=$1 AND process_id=$2 AND analysis_status='success' LIMIT 1",[req.user.organization_id,req.params.processId]);if(!success.rowCount)return res.status(422).json({error:'Completa primero el análisis con IA de esta oportunidad.'});
 const matrix=await ensurePublicMatrix(req.params.processId);
 await query(`INSERT INTO saas.bid_workspaces(organization_id,process_id,matrix_id,started_by_user_id) VALUES($1,$2,$3,$4) ON CONFLICT(organization_id,process_id) DO UPDATE SET matrix_id=EXCLUDED.matrix_id,updated_at=NOW()`,[req.user.organization_id,req.params.processId,matrix.id,req.user.id]);
 await query(`INSERT INTO saas.app_opportunity_states(organization_id,process_id,stage,updated_by_user_id) VALUES($1,$2,'preparing',$3) ON CONFLICT(organization_id,process_id) DO UPDATE SET stage=CASE WHEN saas.app_opportunity_states.stage='submitted' THEN 'submitted' ELSE 'preparing' END,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=NOW()`,[req.user.organization_id,req.params.processId,req.user.id]);
 void runWorkflow('WF-019',{organization_id:req.user.organization_id,process_id:req.params.processId,processing_mode:'single'}).catch(()=>{});
 await writeAudit({organizationId:req.user.organization_id,userId:req.user.id,action:'bid.continued',entityType:'process',entityId:req.params.processId,metadata:{matrix_id:matrix.id,reused:matrix.reused},req});res.status(202).json({matrix_id:matrix.id,reused:matrix.reused});
}catch(e){next(e);}});
bidsRouter.post('/processes/:processId/refresh',edit,limit,async(req,res,next)=>{try{
 const w=await readBidWorkspace(req.user.organization_id,req.params.processId);if(!w.workspace)return res.status(404).json({error:'Primero decide continuar con la oportunidad.'});
 const matrix=await ensurePublicMatrix(req.params.processId);await query('UPDATE saas.bid_workspaces SET matrix_id=$3,updated_at=NOW() WHERE organization_id=$1 AND process_id=$2',[req.user.organization_id,req.params.processId,matrix.id]);
 // A retry is explicit, global and quota-controlled; ready cached chunks are preserved.
 await query(`UPDATE secop.public_document_insights SET status='queued',attempts=0,next_attempt_at=NOW() WHERE status='error' AND updated_at<NOW()-INTERVAL '5 minutes' AND id::text IN (SELECT jsonb_array_elements_text(document_ids) FROM secop.public_process_matrices WHERE id=$1)`,[matrix.id]);
 void runWorkflow('WF-019',{organization_id:req.user.organization_id,process_id:req.params.processId,processing_mode:'single'}).catch(()=>{});res.status(202).json({matrix_id:matrix.id});
}catch(e){next(e);}});
bidsRouter.patch('/processes/:processId/documents/:insightId',edit,async(req,res,next)=>{try{
 if(!uuid.test(req.params.insightId))return res.status(400).json({error:'Documento no válido.'});
 const role=req.body?.role,reason=String(req.body?.reason??'').trim().slice(0,1000);
 if(!['informative','fillable','mixed','not_required'].includes(role)||reason.length<8)return res.status(400).json({error:'Elige una clasificación y explica el motivo (mínimo 8 caracteres).'});
 const data=await readBidWorkspace(req.user.organization_id,req.params.processId);const doc=data.matrix?.documents.find(d=>d.id===req.params.insightId);if(!doc)return res.status(404).json({error:'Documento fuera de la matriz actual.'});
 await query(`UPDATE saas.bid_workspaces SET document_decisions=document_decisions||jsonb_build_object($3::text,$4::jsonb),updated_at=NOW() WHERE organization_id=$1 AND process_id=$2`,[req.user.organization_id,req.params.processId,doc.id,JSON.stringify({role,reason,content_hash:doc.content_hash,user_id:req.user.id,at:new Date().toISOString()})]);
 await writeAudit({organizationId:req.user.organization_id,userId:req.user.id,action:'bid.document_classified',entityType:'process',entityId:req.params.processId,metadata:{document_id:doc.id,role,reason},req});res.json({ok:true});
}catch(e){next(e);}});
bidsRouter.post('/processes/:processId/import-forms',edit,limit,async(req,res,next)=>{try{
 const data=await readBidWorkspace(req.user.organization_id,req.params.processId);if(!data.matrix||data.matrix.stale)return res.status(409).json({error:'Actualiza primero la matriz pública.'});
 const forms=data.matrix.documents.filter(d=>['fillable','mixed'].includes(d.effective_role));const templates=[];
 for(const d of forms){if(d.status!=='ready')continue;templates.push(await importPublicTemplate(req.user.organization_id,req.user.id,req.params.processId,d.id));}
 res.json({templates,pending:forms.length-templates.length});
}catch(e){next(e);}});
bidsRouter.post('/documents/:documentId/preview',previewLimit,async(req,res,next)=>{try{const preview=await ensureDocumentPreview(req.bidDocument);res.json({pages:preview.page_count,hash:preview.pdf_hash,source_hash:preview.source_hash,pdf_url:`/api/bids/documents/${req.params.documentId}/preview.pdf`});}catch(e){next(e);}});
bidsRouter.get('/documents/:documentId/preview.pdf',async(req,res,next)=>{try{const p=(await query('SELECT * FROM saas.generated_document_previews WHERE generated_document_id=$1 AND organization_id=$2 AND source_hash=$3',[req.params.documentId,req.user.organization_id,req.bidDocument.file_hash_sha256])).rows[0];if(!p)return res.status(404).json({error:'Genera primero la vista previa de esta versión.'});res.set({'Content-Type':'application/pdf','Content-Disposition':'inline; filename="vista-previa.pdf"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}).send(await readStoredDocument(p.storage_key));}catch(e){next(e);}});
bidsRouter.get('/documents/:documentId/pages/:page',previewLimit,async(req,res,next)=>{try{const n=Number(req.params.page);const p=(await query('SELECT * FROM saas.generated_document_previews WHERE generated_document_id=$1 AND organization_id=$2 AND source_hash=$3',[req.params.documentId,req.user.organization_id,req.bidDocument.file_hash_sha256])).rows[0];if(!p||!Number.isInteger(n)||n<1||n>p.page_count)return res.status(404).json({error:'Página no disponible.'});const image=await previewPage(await readStoredDocument(p.storage_key),n);res.set({'Content-Type':'image/png','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}).send(image);}catch(e){next(e);}});
bidsRouter.post('/documents/:documentId/review',edit,async(req,res,next)=>{try{
 const g=req.bidDocument;if(req.body?.confirmed!==true||req.body?.source_hash!==g.file_hash_sha256)return res.status(409).json({error:'Confirma la revisión de la versión actual.'});
 if(blockingIssues(g.validation_issues).length)return res.status(422).json({error:'Corrige los campos pendientes antes de aprobar el documento.'});
 const latest=(await query('SELECT id FROM saas.generated_template_documents WHERE organization_id=$1 AND template_id=$2 AND process_id IS NOT DISTINCT FROM $3 ORDER BY created_at DESC,id DESC LIMIT 1',[req.user.organization_id,g.template_id,g.process_id])).rows[0];
 if(latest?.id!==g.id||g.version_number!==g.current_version)return res.status(409).json({error:'Hay una versión más reciente. Previsualízala y revísala.'});
 const p=(await query('SELECT pdf_hash FROM saas.generated_document_previews WHERE generated_document_id=$1 AND organization_id=$2 AND source_hash=$3',[g.id,req.user.organization_id,g.file_hash_sha256])).rows[0];if(!p||req.body?.preview_hash!==p.pdf_hash)return res.status(409).json({error:'Abre primero la previsualización de esta versión.'});
 await query(`INSERT INTO saas.generated_document_reviews(generated_document_id,organization_id,source_hash,preview_hash,reviewed_by_user_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(generated_document_id) DO UPDATE SET source_hash=EXCLUDED.source_hash,preview_hash=EXCLUDED.preview_hash,reviewed_by_user_id=EXCLUDED.reviewed_by_user_id,reviewed_at=NOW()`,[g.id,req.user.organization_id,g.file_hash_sha256,p.pdf_hash,req.user.id]);
 await writeAudit({organizationId:req.user.organization_id,userId:req.user.id,action:'bid.document_reviewed',entityType:'generated_document',entityId:g.id,metadata:{file_hash:g.file_hash_sha256,preview_hash:p.pdf_hash},req});res.json({approved:true});
}catch(e){next(e);}});
bidsRouter.post('/processes/:processId/export',edit,limit,async(req,res,next)=>{try{
 const data=await readBidWorkspace(req.user.organization_id,req.params.processId);
 if(!data.workspace||!data.matrix||req.body?.matrix_revision!==data.matrix.revision_hash)return res.status(409).json({error:'El proceso cambió. Actualiza y revisa el paquete.'});
 if(data.blockers.length)return res.status(422).json({error:'Hay documentos pendientes de preparar o revisar.',blockers:data.blockers});
 if(req.body?.confirmed!==true)return res.status(400).json({error:'Confirma que revisaste los documentos y soportes seleccionados.'});
 const supportIds=[...new Set(Array.isArray(req.body?.support_ids)?req.body.support_ids:[])];if(supportIds.length>100||supportIds.some(id=>!uuid.test(id)))return res.status(400).json({error:'Selección de soportes no válida.'});
 const generated=(await query(`SELECT g.*,t.name,p.storage_key AS preview_storage_key,p.pdf_hash FROM saas.generated_template_documents g JOIN saas.document_templates t ON t.id=g.template_id JOIN saas.generated_document_previews p ON p.generated_document_id=g.id AND p.organization_id=$1 WHERE g.organization_id=$1 AND g.process_id=$2 AND g.id=ANY($3::uuid[])`,[req.user.organization_id,req.params.processId,data.templates.map(t=>t.generated_id)])).rows;
 const supports=(await query(`SELECT * FROM saas.organization_documents WHERE organization_id=$1 AND id=ANY($2::uuid[]) AND document_status<>'deleted' AND storage_key IS NOT NULL`,[req.user.organization_id,supportIds])).rows;
 if(generated.length!==data.templates.length)return res.status(409).json({error:'Cambió un formulario del paquete. Actualiza y revisa de nuevo.'});
 if(supports.some(s=>req.body?.support_hashes?.[s.id]!==s.file_hash_sha256))return res.status(409).json({error:'Cambió un soporte seleccionado. Vuelve a revisarlo.'});
 if(supports.length!==supportIds.length)return res.status(409).json({error:'Un soporte seleccionado ya no está disponible.'});
 if(!generated.length&&!supports.length)return res.status(422).json({error:'Selecciona al menos un documento necesario para la oferta.'});
 const files=[];let total=0;async function append(storage,name,expectedHash){const buffer=await readStoredDocument(storage);if(!buffer||fileSha256(buffer)!==expectedHash)throw Object.assign(Error('Un archivo cambió o no está disponible; revisa el paquete.'),{statusCode:409});total+=buffer.length;if(total>150*1024*1024)throw Object.assign(Error('El paquete supera 150 MB. Reduce los soportes seleccionados.'),{statusCode:413});files.push({name,buffer,sha256:expectedHash});}
 for(const g of generated){const ext=g.mime_type==='application/pdf'?'.pdf':g.mime_type.includes('spreadsheetml')?'.xlsx':'.docx';const name=zipName(g.name).replace(/\.(pdf|docx|xlsx)$/i,'')+'-'+g.id.slice(0,8);await append(g.storage_key,`01_formularios/${name}${ext}`,g.file_hash_sha256);if(ext!=='.pdf')await append(g.preview_storage_key,`03_vistas_pdf/${name}.pdf`,g.pdf_hash);}
 for(const s of supports){if(s.malware_scan_status==='infected'||s.document_status==='rejected')return res.status(422).json({error:`El soporte ${s.document_name} no puede exportarse.`});await append(s.storage_key,`02_soportes/${s.id.slice(0,8)}-${zipName(s.original_filename||s.document_name)}`,s.file_hash_sha256);}
 const manifest={process_id:req.params.processId,reference:req.bidProcess.reference,matrix_revision:data.matrix.revision_hash,created_at:new Date().toISOString(),files:files.map(({buffer,...f})=>({...f,bytes:buffer.length})),reviewed_documents:data.templates.map(t=>({id:t.generated_id,reviewed_at:t.reviewed_at})),notice:'Revisa firmas, vigencias y el cronograma antes de cargar los archivos en SECOP. Las vistas PDF acompañan a los originales editables.'};
 await query('INSERT INTO saas.bid_exports(organization_id,process_id,created_by_user_id,manifest) VALUES($1,$2,$3,$4::jsonb)',[req.user.organization_id,req.params.processId,req.user.id,JSON.stringify(manifest)]);
 res.set({'Content-Type':'application/zip','Content-Disposition':`attachment; filename="oferta.zip"; filename*=UTF-8''${encodeURIComponent("oferta-"+zipName(req.bidProcess.reference||req.params.processId)+".zip")}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'});
 const archive=new ZipArchive({zlib:{level:6}});archive.on('error',error=>{if(res.headersSent)res.destroy(error);else next(error);});res.on('close',()=>{if(!res.writableEnded)archive.abort();});archive.pipe(res);for(const f of files)archive.append(f.buffer,{name:f.name});archive.append(JSON.stringify(manifest,null,2),{name:'00_control_del_paquete.json'});await archive.finalize();
}catch(e){next(e);}});
