export const DOCUMENT_TYPES = [
  ["chamber_of_commerce", "Certificado de Cámara de Comercio"],
  ["rut", "Registro Único Tributario (RUT)"],
  ["fiscal_background", "Antecedentes fiscales"],
  ["disciplinary_background", "Antecedentes disciplinarios"],
  ["police_background", "Antecedentes de Policía"],
  ["judicial_measures", "Medidas correctivas"],
  ["experience_certificate", "Certificado de experiencia"],
  ["financial_statement", "Estado financiero"],
  ["quality_certificate", "Certificación de calidad"],
  ["identity_document", "Documento de identidad"],
  ["rup", "Registro Único de Proponentes (RUP)"],
  ["company_portfolio", "Portafolio empresarial"],
  ["employment_certificate", "Certificado de vinculación laboral"],
  ["professional_qualification", "Título o matrícula profesional"],
  ["equipment_inventory", "Inventario o disponibilidad de equipos"],
  ["execution_record", "Acta de recibo o liquidación"],
  ["contract", "Contrato suscrito"],
  ["bank_certificate", "Certificado bancario"],
  ["education_certificate", "Certificado académico"],
  ["social_security_payment", "Planilla de seguridad social"],
  ["military_status", "Certificado de situación militar"],
  ["redam_certificate", "Certificado REDAM"],
  ["victim_certificate", "Certificado de víctimas"],
  ["other_document", "Otro documento"],
] as const;

