import Link from "next/link";
import { PublicSite, PageHeading, ClosingCTA } from "@/app/components/public-site";
import { SecopComparison } from "@/app/components/secop-comparison";
import { pageMetadata } from "@/lib/seo";
export const metadata=pageMetadata("/licitaciones-secop","Licitaciones SECOP: encuentra y analiza con IA | CernoIA","Encuentra oportunidades de SECOP para tu empresa. Analiza requisitos, organiza documentos y prepara propuestas con CernoIA. Conoce los planes de membresía.");
export default function Page(){return <PublicSite><PageHeading label="Licitaciones SECOP en Colombia" title="Encuentra oportunidades. Evalúa si tu empresa puede participar.">CernoIA conecta procesos de contratación pública con el perfil y los documentos de tu empresa. Usa la inteligencia artificial como apoyo para revisar requisitos y preparar una propuesta con más contexto.</PageHeading>
<section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="max-w-3xl"><h2 className="text-3xl font-semibold">De la búsqueda en SECOP al análisis de tu oportunidad</h2><p className="mt-5 leading-8 text-slate-600">Ver una licitación no basta para decidir. Tu equipo necesita entender el objeto del proceso, el territorio, los plazos y lo que debe acreditar. CernoIA reúne oportunidades y documentación empresarial para ayudarte a priorizar qué revisar y qué preparar.</p><p className="mt-4 leading-8 text-slate-600">Empieza con los servicios, la experiencia y los intereses de tu empresa. Consulta procesos, revisa su afinidad y contrasta los requisitos con tus soportes. La afinidad orienta la búsqueda; el cumplimiento se comprueba en los documentos y condiciones vigentes.</p></div>
<div className="mt-10 grid gap-6 md:grid-cols-3">{[
["Encuentra procesos relevantes","Filtra oportunidades y explora la contratación por territorio y entidad. Guarda los procesos que interesan a tu equipo y organiza su seguimiento."],
["Identifica requisitos y pendientes","Reúne documentos de experiencia, capacidad financiera y certificaciones. Contrasta los soportes con lo solicitado e identifica información que necesita revisión."],
["Prepara la propuesta con tu equipo","Utiliza el asistente y las plantillas para preparar borradores. Revisa cada dato, completa los pendientes y confirma el procedimiento de presentación en la fuente oficial."]
].map(([title,text])=><article key={title} className="rounded-2xl border border-[#dce4e3] bg-white p-7"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p></article>)}</div><Link href="/capacidades" className="mt-8 inline-block font-semibold text-teal-800 underline">Conocer las funciones de CernoIA →</Link></section>
<SecopComparison />
<section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="grid gap-12 md:grid-cols-2"><div><h2 className="text-3xl font-semibold">Qué revisar antes de avanzar</h2><ul className="mt-6 list-disc space-y-3 pl-5 leading-7 text-slate-600"><li>El alcance del proceso y su relación con los servicios de tu empresa.</li><li>Las fechas, adendas y documentos publicados por la entidad.</li><li>Los requisitos y las evidencias que puedes aportar.</li><li>Los pendientes de tu equipo y el canal de presentación de la oferta.</li></ul><p className="mt-5 leading-7 text-slate-600">Consulta siempre la información vigente en <a href="https://www.colombiacompra.gov.co/secop/secop-ii" className="font-semibold text-teal-800 underline">SECOP II de Colombia Compra Eficiente</a>. CernoIA no garantiza adjudicaciones ni presenta ofertas automáticamente.</p></div><div><h2 className="text-3xl font-semibold">Cómo empezar con la membresía</h2><p className="mt-6 leading-7 text-slate-600">Revisa los planes y solicita acceso para tu empresa. El alta se realiza por organización e invitación; una vez confirmada, podrás consultar el importe aplicable y pagar en Bold. La activación depende de la confirmación del pago.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/planes" className="rounded-full bg-[#0b5963] px-6 py-3 font-semibold text-white">Ver planes y solicitar membresía</Link><Link href="/como-funciona" className="rounded-full border border-teal-700 px-6 py-3 font-semibold text-teal-800">Ver cómo funciona</Link></div><p className="mt-6 text-sm leading-6 text-slate-600">¿Estás empezando a explorar contratación pública? Lee nuestras <Link href="/articulos" className="font-semibold text-teal-800 underline">guías de SECOP, requisitos y documentos</Link>.</p></div></div></section><ClosingCTA /></PublicSite>;}
