import { pageMetadata } from "@/lib/seo";
import { PublicSite, PageHeading, ClosingCTA } from "@/app/components/public-site";
export const metadata = pageMetadata("/como-funciona", "Cómo encontrar y analizar oportunidades SECOP | CernoIA", "Conoce cómo CernoIA conecta tu perfil empresarial con oportunidades de SECOP. Analiza requisitos, organiza documentos y prepara propuestas con tu equipo.");
export default function Page() { return <PublicSite><PageHeading label="Cómo funciona" title="Del perfil de tu empresa a una decisión revisable.">Configura lo que tu empresa puede demostrar, encuentra procesos compatibles, revisa sus requisitos y prepara los pendientes junto con tu equipo.</PageHeading><section className="mx-auto grid max-w-7xl gap-5 px-6 py-16 md:grid-cols-2 lg:px-10 lg:py-20">{[
["01", "Configura tu empresa", "El administrador crea el espacio de la organización e invita a tu equipo. Completa el perfil empresarial, las capacidades y los intereses de búsqueda."],
["02", "Reúne tus documentos", "Carga la documentación de tu empresa. Revisa el contenido extraído, su vigencia y los datos que utilizarás en plantillas y propuestas."],
["03", "Explora y analiza", "Consulta procesos y afinidades, revisa requisitos y utiliza el chat para profundizar en el contexto. Confirma fechas y condiciones en la fuente oficial."],
["04", "Prepara y revisa", "Organiza los pendientes y genera un borrador de propuesta. Tu equipo revisa y aprueba el resultado antes de presentarlo por los canales correspondientes."]
].map(([n,title,text])=><article key={n} className="public-step-card rounded-2xl border border-[#dce4e3] bg-white p-8 shadow-sm md:p-9"><div className="relative flex items-center justify-between"><span className="flex size-12 items-center justify-center rounded-xl bg-[#082f38] font-mono text-sm text-teal-300">{n}</span><span className="text-xs font-semibold uppercase tracking-[.18em] text-teal-700">Paso {n}</span></div><h2 className="relative mt-7 text-2xl font-semibold tracking-tight">{title}</h2><p className="relative mt-4 leading-7 text-slate-600">{text}</p></article>)}</section><ClosingCTA /></PublicSite>; }
